Updated Actions workflow for ssh server connection

diff --git a/.github/workflows/java-ci.yml b/.github/workflows/java-ci.yml
--- a/.github/workflows/java-ci.yml
+++ b/.github/workflows/java-ci.yml
@@ -23,18 +23,54 @@ jobs:
 
     steps:
     - uses: actions/checkout@v3
+
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'
+
     - name: Set execute permissions on gradlew
       run: chmod +x ./gradlew
+
+    - name: SSH Tunnel
+      env:
+        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
+        SSH_SERVER_IP: ${{ secrets.SSH_SERVER_IP }}
+        SSH_PORT: ${{ secrets.SSH_PORT }}
+      run: |
+        # Start SSH agent and add the private key
+        eval $(ssh-agent -s)
+        ssh-add <(echo "$SSH_PRIVATE_KEY")
+
+        # Create an SSH tunnel for MySQL
+        ssh -f -N -L 3306:127.0.0.1:3306 $SSH_USERNAME@$SSH_SERVER_IP -p $SSH_PORT
+
     - name: Build with Gradle
       env:
-        DB_HOST: ${{ secrets.DB_HOST }}
+        DB_HOST: 127.0.0.1
         DB_PORT: ${{ secrets.DB_PORT }}
         DB_NAME: ${{ secrets.DB_NAME }}
         DB_USERNAME: ${{ secrets.DB_USERNAME }}
         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
-      run: ./gradlew build
+      run: |
+        # Add error handling - exit if any command returns a non-zero status
+        set -e
+
+        # Execute Gradle build
+        ./gradlew build
+
+#    - name: Run Tests
+#      env:
+#        DB_HOST: 127.0.0.1
+#        DB_PORT: ${{ secrets.DB_PORT }}
+#        DB_NAME: ${{ secrets.DB_NAME }}
+#        DB_USERNAME: ${{ secrets.DB_USERNAME }}
+#        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+#      run: |
+#        # Add error handling - exit if any command returns a non-zero status
+#        set -e
+#
+#        # Execute Gradle tests
+#        ./gradlew test
